// Generated by gencpp from file rospy_tutorial/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROSPY_TUTORIAL_MESSAGE_ADDTWOINTS_H
#define ROSPY_TUTORIAL_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <rospy_tutorial/AddTwoIntsRequest.h>
#include <rospy_tutorial/AddTwoIntsResponse.h>


namespace rospy_tutorial
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace rospy_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rospy_tutorial::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::rospy_tutorial::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::rospy_tutorial::AddTwoInts > {
  static const char* value()
  {
    return "rospy_tutorial/AddTwoInts";
  }

  static const char* value(const ::rospy_tutorial::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::rospy_tutorial::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::rospy_tutorial::AddTwoInts > 
template<>
struct MD5Sum< ::rospy_tutorial::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rospy_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::rospy_tutorial::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rospy_tutorial::AddTwoIntsRequest> should match 
// service_traits::DataType< ::rospy_tutorial::AddTwoInts > 
template<>
struct DataType< ::rospy_tutorial::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::rospy_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::rospy_tutorial::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rospy_tutorial::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::rospy_tutorial::AddTwoInts > 
template<>
struct MD5Sum< ::rospy_tutorial::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rospy_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::rospy_tutorial::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rospy_tutorial::AddTwoIntsResponse> should match 
// service_traits::DataType< ::rospy_tutorial::AddTwoInts > 
template<>
struct DataType< ::rospy_tutorial::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::rospy_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::rospy_tutorial::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSPY_TUTORIAL_MESSAGE_ADDTWOINTS_H
